"""Reviewed provider facts; Alpharch readiness is separate from vendor capability."""

REVIEWED = '2026-09-05'

def entry(slug, name, category, route, linux, status, summary, needs, steps, trouble, sources, related=()):
    return dict(slug=slug, name=name, category=category, route=route, linux=linux,
                status=status, summary=summary, needs=needs, steps=steps,
                trouble=trouble, sources=sources, related=list(related), reviewed=REVIEWED)

PROVIDERS = [
entry('interactive-brokers','Interactive Brokers','Futures brokers','TWS / IB Gateway','Native Linux software','planned',
      'IBKR supplies Linux builds of TWS and IB Gateway. An Alpharch connection through the TWS API still needs an adapter and account testing.',
      ['An IBKR account and its required market-data subscriptions.','The Linux TWS or IB Gateway application, signed in locally.'],
      [('Install the official Linux application','Download TWS or IB Gateway from IBKR. Gateway uses fewer desktop resources; TWS also lets you inspect the same data in its own interface.'),
       ('Prepare the local API connection','In the application’s API settings, enable socket clients, retain read-only access for charting, and note the socket port. Keep access on this computer.'),
       ('Confirm your market data','Check the exact futures contract and exchange in IBKR. Quotes, tick-by-tick subscriptions and market depth have different permissions and limits.'),
       ('Connect when the Alpharch adapter is available','The planned flow selects the local gateway, port and environment. This guide does not mean an IBKR account can connect to the current Alpharch release.')],
      [('Gateway opens but no chart data','Check that you are signed in, the API is enabled and the socket port matches. A successful socket connection alone does not establish a market-data entitlement.'),
       ('A ladder or footprint is missing detail','Check depth and tick-by-tick permissions and subscription limits. Ordinary watchlist quotes do not establish full-depth or market-by-order coverage.')],
      [('Linux downloads','https://www.interactivebrokers.com/en/trading/ibgateway-latest.php?menu=A'),('TWS / Gateway setup','https://www.interactivebrokers.com/campus/trading-lessons/installing-configuring-tws-for-the-api/'),('Tick-by-tick data limits','https://www.interactivebrokers.com/docs/tws-api/doc/market-data-live/tick-by-tick-data/request-tick-by-tick-data')]),
entry('rithmic','Rithmic','Data & routing','Rithmic R | Protocol API','Cross-platform protocol','access',
      'Rithmic is a data and routing provider used by multiple futures brokers. Its WebSocket/protobuf protocol is a route for a Linux integration; R | Trader Pro itself is a Windows application.',
      ['Broker-issued Rithmic credentials, system name and market-data permissions.','Alpharch developer-kit access, implementation and successful conformance before production use.'],
      [('Find your feed credentials','Use the Rithmic login issued for your trading account. Your broker’s customer-portal password may be different.'),('Confirm the system and subscriptions','Ask the broker which Rithmic system your account uses, whether third-party access is enabled, and what depth is included.'),('Check Alpharch availability','The adapter is not released. Production requires Rithmic conformance; personal credentials alone cannot enable an unapproved application.')],
      [('Login works elsewhere but not in another platform','Verify the exact system, application permission and simultaneous-session allowance with the broker.'),('Expecting MBO detail','Confirm that the account and integration deliver individual-order data. Level-2 availability by itself is not proof of MBO coverage.')],
      [('Developer access and conformance','https://www.rithmic.com/documentation'),('Rithmic desktop and protocol products','https://www.rithmic.com/products')]),
entry('cqg','CQG','Data & routing','CQG Web API','Cross-platform Web API','access',
      'CQG can connect a Linux application through its Web API. Production access requires application identifiers and conformance; browser authorization also requires CQG app registration.',
      ['A CQG account enabled by the broker for the intended application and exchanges.','Alpharch registration, adapter implementation and production conformance.'],
      [('Identify the CQG account','Use the CQG credentials supplied for your trading platform, not an unrelated broker-portal login.'),('Check account access','Confirm the exchange subscriptions and third-party platform permissions with your broker.'),('Use the supported authorization route when released','CQG documents user logon and registered OAuth with PKCE. Alpharch has not released either route; this website does not collect credentials.')],
      [('Application or private-label error','The software’s CQG registration must match the account’s permissions. This is not fixed by repeatedly changing your password.'),('Quotes without depth','Ask for the data entitlement needed for the exact contract and view. Top-of-book access does not supply a full ladder.')],
      [('CQG logon requirements','https://help.cqg.com/apihelp/Documents/logon.htm'),('CQG browser authorization','https://partners.cqg.com/deployment/cqg-desktop-integrations/cqg-oauth-2_0-documentation')]),
entry('tradovate','Tradovate','Futures brokers','Tradovate API / OAuth','Cross-platform web API','access',
      'Tradovate documents a web API with OAuth and separate live, simulation and market-data services. Account eligibility and API access must be confirmed before an Alpharch integration can be used.',
      ['An eligible account with API access and the required exchange subscriptions.','A registered and tested Alpharch integration. Prop-firm access must be checked separately.'],
      [('Confirm API eligibility','Check the current API-access requirements in Tradovate’s official documentation and your account settings. A platform login is not proof of API access.'),('Identify the environment','Keep live and simulation accounts distinct. Market-data permission is separate from the ability to sign in.'),('Authorize when supported','A released third-party connection should direct you through the supported authorization flow. Alpharch’s Tradovate adapter is not available yet.')],
      [('Demo or prop account will not authorize','Ask the account provider whether third-party API use is allowed for that specific account.'),('Account appears but quotes do not','Check API and exchange-data permissions, then the exact contract symbol and environment.')],
      [('API access, OAuth and market data','https://api.tradovate.com/')]),
entry('ninjatrader','NinjaTrader','Futures brokers','Account-specific connection','Verify the account route','verify',
      'A NinjaTrader login does not automatically authorize another charting application. NinjaTrader’s account FAQ documents Continuum / CQG credentials for applicable accounts; confirm your account’s actual route.',
      ['Written confirmation of the connection available to your specific account.','A tested Alpharch adapter for that route.'],
      [('Find the account’s connection details','Check your account documentation or ask NinjaTrader which third-party data route is enabled.'),('Match the route','If you were issued CQG credentials, read the CQG guide. Only use Tradovate API instructions if that route is explicitly enabled for your account.'),('Check release support','NinjaTrader is not a working broker connection in the current Alpharch release.')],
      [('NinjaTrader website password is rejected','Brokerage, website and data-provider credentials can serve different purposes. Confirm the required login instead of trying every connection type.')],
      [('NinjaTrader account FAQ','https://www.ninjatrader.com/ninjatrader-account-faqs/')],('cqg','tradovate')),
entry('amp-futures','AMP Futures','Futures brokers','CQG / Rithmic / TT / Teton','Depends on the selected route','access',
      'AMP advertises several data and routing choices. Alpharch must support the particular route enabled on your account; an AMP customer-portal login is not a universal market-data login.',
      ['Your enabled platform/data route and its separate login.','Exchange subscriptions appropriate to quotes or depth.'],
      [('Check your AMP platform setup','Find which data provider was selected for your account. Do not change subscriptions merely to try an unreleased adapter.'),('Choose the matching guide','Use the CQG or Rithmic page for those routes. TT and Teton do not have an Alpharch adapter.'),('Verify access with AMP','Confirm the requested application and depth permissions before a future connection attempt.')],
      [('Quotes are available but the ladder is empty','AMP lists top-of-book and depth subscriptions separately. Check the exchange and subscription level.'),('Connection fails during the weekend','Check the provider’s maintenance status before changing credentials.')],
      [('AMP platform and feed choices','https://www.ampfutures.com/'),('AMP data subscriptions','https://www.ampfutures.com/trading-info/exchange-data-fees')],('cqg','rithmic')),
entry('edgeclear','EdgeClear','Futures brokers','Rithmic / CQG / CTS / Teton','Depends on the selected route','access',
      'EdgeClear lists Rithmic, CQG, Teton and CTS. Confirm which provider is attached to your account before choosing a connection.',
      ['Your actual feed credentials and exchange permissions.','A released adapter for that provider.'],
      [('Identify your feed','Find the provider on your setup confirmation or ask EdgeClear.'),('Read the route guide','Rithmic and CQG have separate guides here. CTS and Teton are not implemented in Alpharch.'),('Confirm application permission','Ask whether the account can use the intended third-party platform and whether a concurrent connection is allowed.')],
      [('An EdgeClear portal login does not connect','Use the data-provider credentials issued for the account, once the matching Alpharch adapter is released.')],
      [('EdgeClear supported data feeds','https://support.edgeclear.com/portal/en/kb/articles/what-data-feeds-does-edgeclear-offer')],('rithmic','cqg')),
entry('optimus-futures','Optimus Futures','Futures brokers','Broker-issued data route','Depends on the selected route','access',
      'Optimus supports several platforms and separates account/statement logins from platform logins. Its support documentation identifies Rithmic and CQG routes for Optimus Flow.',
      ['The data route and platform login assigned to your account.','Permission to connect a supported third-party application.'],
      [('Find the platform login','Do not confuse your clearing-firm statements login with a trading-platform login.'),('Check the assigned data provider','Confirm Rithmic, CQG or another route with Optimus.'),('Follow that provider’s guide','The broker relationship does not remove Alpharch’s adapter and approval requirements.')],
      [('The portal works but market data does not','Verify the platform credentials and exchange-data permissions with the account provider.')],
      [('Optimus account and platform logins','https://optimusfutures.com/account-login.php'),('Optimus Flow routing','https://support.optimusfutures.com/trading-platform-routing-fees')],('rithmic','cqg')),
entry('tradestation','TradeStation','Futures brokers','TradeStation API / OAuth','Cross-platform HTTPS API','access',
      'TradeStation exposes brokerage and market-data services over HTTPS, with a separate simulation service. Its developer onboarding uses an API key and OAuth.',
      ['An account with the required products and data permissions.','Approved application access and an implemented Alpharch OAuth adapter.'],
      [('Confirm developer access','Review TradeStation’s API onboarding and permissions for the intended account.'),('Separate data from account access','Identify the futures instruments and streaming data needed for your charts.'),('Authorize only when supported','The planned connection is browser authorization. Alpharch does not currently provide a working TradeStation login.')],
      [('Expecting the desktop app to be required','The documented API is HTTPS-based. Linux feasibility comes from that API, not from a claim that TradeStation’s desktop software runs natively on Omarchy.')],
      [('API documentation','https://api.tradestation.com/docs/'),('API onboarding','https://www.tradestation.com/insights/getting-started-with-a-trading-platform-api/')]),
entry('tastytrade','tastytrade','Futures brokers','OAuth / streaming market data','Cross-platform web API','access',
      'tastytrade documents futures and crypto access through its Open API. Current authentication uses OAuth; third-party applications require verification before other users can authorize them.',
      ['An eligible account with market-data permissions.','A verified third-party application and a tested Alpharch adapter.'],
      [('Review current OAuth requirements','Use the current tastytrade developer guide. The former password-session flow was retired in February 2026.'),('Check product and data permissions','Futures, options and crypto availability depend on your account and the requested data.'),('Authorize when an integration is released','Alpharch has not released a tastytrade adapter. Do not enter a broker password on this website.')],
      [('An old tutorial uses a password session','Follow the current OAuth documentation; legacy session examples are obsolete.'),('Sandbox credentials fail in production','tastytrade separates sandbox and production credentials and data.')],
      [('OAuth authentication and third-party verification','https://developer.tastytrade.com/docs/authentication/oauth2/'),('Open API products','https://developer.tastytrade.com/')]),
entry('ironbeam','Ironbeam','Futures brokers','Ironbeam REST / streaming API','Cross-platform web API','access',
      'Ironbeam documents token authentication, symbol search, entitled exchanges and streams for quotes, depth and trades. It offers distinct demo and live services.',
      ['API-enabled account access from Ironbeam and exchange permissions.','An implemented and tested Alpharch integration.'],
      [('Confirm account API access','Ask Ironbeam whether the intended account is enabled for the API and requested environment.'),('Check symbols and entitled exchanges','Use the account’s actual instruments and data permissions; a successful login alone is insufficient.'),('Connect once released','Alpharch’s Ironbeam adapter is not available. A future local connection must authenticate against the correct demo or live service.')],
      [('Account connects but the symbol is unknown','Check the provider’s symbol search and contract expiry.'),('No depth stream','Verify exchange entitlement and a separate depth subscription.')],
      [('Ironbeam API overview','https://www.ironbeam.com/api/'),('Authentication and stream reference','https://docs.ironbeamapi.com/')]),
entry('stonex','StoneX','Futures brokers','Account-specific CQG route','Cross-platform route where enabled','access',
      'StoneX publishes a directory of third-party futures platforms using CQG. Whether a given StoneX account can use Alpharch requires confirmation and a released CQG adapter.',
      ['The platform/data route enabled for your StoneX account.','Provider credentials and exchange permissions.'],
      [('Confirm the route with StoneX','Ask which third-party connection is enabled for your account.'),('Keep the logins separate','Use provider-issued platform credentials for market data, not the account-management login.'),('Read the CQG guide if applicable','Other StoneX services should not be assumed to use the same connection.')],
      [('A StoneX login is rejected by CQG','Confirm that the account was provisioned for the specific CQG platform and use its assigned credentials.')],
      [('StoneX third-party CQG platforms','https://futures.stonex.com/third-party-software')],('cqg',)),
entry('dorman','Dorman Trading','Futures brokers','Confirm through the broker / FCM','Route not yet verified','verify',
      'Dorman offers a range of third-party trading technology. The clearing relationship alone does not identify the data API or authorize an Alpharch connection.',
      ['Your platform setup confirmation, actual provider and exchange entitlements.'],
      [('Identify the account’s platform','Ask the introducing broker or Dorman for the exact data route and login instructions.'),('Check third-party permissions','Confirm whether another application may consume that feed and what subscriptions are needed.'),('Match a supported adapter','No Dorman-specific connection is released in Alpharch. Use a provider guide only after the account route is confirmed.')],
      [('Unsure whether to select Dorman or a feed provider','The FCM holds the account; the feed route determines the software integration.')],
      [('Dorman trading technology','https://www.dormantrading.com/home/home-trading-technology/')]),
entry('phillip-capital','Phillip Capital','Futures brokers','Account-specific platform setup','Route must be confirmed','verify',
      'Phillip Capital describes support for authorized trading platforms through its broker relationships. Confirm the platform and account permissions assigned to you; a clearing account is not a generic charting API.',
      ['The electronic-trading setup confirmation and actual provider credentials.'],
      [('Review the platform setup','Find the platform approved for your account and the exchanges enabled.'),('Ask about third-party use','Confirm the route available to an external Linux charting application.'),('Check Alpharch support','No Phillip Capital-specific adapter is released. If CQG or Rithmic is assigned, review the matching guide.')],
      [('Account exists but a platform cannot sign in','Platform provisioning and product access must be confirmed separately.')],
      [('Phillip Capital platform and broker support','https://www.phillipcapital.com/ib-partnerships')],('cqg','rithmic')),
entry('schwab','Charles Schwab / thinkorswim','Futures brokers','Developer access requires review','Futures API route not verified','verify',
      'Schwab has a developer portal, but this review could not verify the futures market-data permissions needed for Alpharch from its public portal. thinkorswim access should not be treated as automatic external API access.',
      ['Confirmation from Schwab of futures data available to the intended application and account.'],
      [('Check the developer portal','Review the applicable API product and approval requirements in your Schwab developer account.'),('Ask specifically about futures data','Confirm streaming quotes, trades, depth and historical coverage separately; do not infer them from access in thinkorswim.'),('Wait for verified support','Alpharch has no working Schwab adapter. We are not publishing a speculative login procedure.')],
      [('A third-party example claims support','Verify the exact endpoint and permissions in current official documentation before relying on it.')],
      [('Schwab developer portal','https://developer.schwab.com/products/trader-api--individual')]),
]

def crypto(slug, name, route, fact, source, status='planned', detail=None, steps=None, trouble=None):
    return entry(slug,name,'Crypto exchanges',route,'Cross-platform market-data API',status,fact,
      ['A supported Alpharch adapter for this exchange and product.','Regional availability and the provider’s current data-use conditions.'],
      steps or [('Choose the exact market','Keep spot, perpetuals and dated futures distinct. The same ticker can represent different instruments.'),('Use public data when supported','Public market-data channels do not require linking a trading account. Private account features use a separate authorization path.'),('Check Alpharch availability', detail or 'This exchange has not been integrated into Alpharch. The documented API is a development route, not a working connection in the current release.')],
      trouble or [('Price differs from another venue','Check the exchange, product, quote currency and contract. Do not substitute another exchange’s price.'),('Connection unavailable in your region','Use a provider available to you. Do not bypass regional access restrictions.')],
      [(name+' official API documentation',source)])

PROVIDERS += [
crypto('binance-us','Binance.US','Separate public spot API',
       'Binance.US has its own API documentation and market-data endpoints. It must not reuse a Binance global connection or be presented as the same derivatives service. Alpharch has no Binance.US adapter.',
       'https://docs.binance.us/'),
crypto('gemini','Gemini','Public market data / private authorization',
       'Gemini documents public prices, order books and trades without credentials. Private features have separate authorization and product permissions. Alpharch has not released a Gemini adapter.',
       'https://developer.gemini.com/'),
crypto('coinbase','Coinbase','Public Exchange market data',
       'Coinbase Exchange separates public market data from authenticated trading APIs. Alpharch already uses public Coinbase spot trades and book data; connecting that feed does not require a trading login.',
       'https://docs.cdp.coinbase.com/exchange/introduction/welcome','existing',
       steps=[('Open the current flow tool','In the installed Alpharch command line, launch alphad --exchange coinbase --market spot --symbol BTC-USD.'),('Choose a view','Use the flow, depth, heatmap, tape or profile views. No Coinbase password or API key is needed for this public feed.'),('Try the development desk when available','The new chart desk supports Coinbase BTC, ETH and SOL against USD. It is a development build; do not assume the public installer already includes it.')]),
crypto('hyperliquid','Hyperliquid','Public perpetual market data',
       'Hyperliquid documents public trade and order-book subscriptions. Alpharch already reads its public perpetual feed without signing a wallet transaction or linking an account.',
       'https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions','existing',
       steps=[('Open the current perpetual flow tool','Launch alphad --exchange hyperliquid --market perp --symbol BTC.'),('Inspect the feed','Check the venue and perpetual label before comparing prices. Book history begins when the connection starts.'),('Use the development chart desk when available','BTC, ETH and SOL perpetuals are available in the development desk. Public data requires no wallet secret or transaction signature.')]),
crypto('deribit','Deribit','Public options / separate private API',
       'Deribit separates public data methods from authenticated private account methods. Alpharch’s existing alphaopt tool uses public options data; it is separate from the new chart desk.',
       'https://docs.deribit.com/','existing',
       steps=[('Open the options tool','Launch alphaopt from the installed Alpharch tools. Read its help for supported assets and views.'),('Choose the options view','The existing tool includes a tape and open-interest map. Open interest is not the same thing as traded flow or dealer positioning.'),('Keep the account separate','Reading this public options feed does not connect an account or enable execution. The new desk does not yet contain a full Deribit chart adapter.')]),
crypto('binance','Binance','Public spot / perpetual streams',
       'Binance publishes spot WebSocket market streams. Alpharch retains legacy Binance spot and perpetual parsers, but connections from this test location returned HTTP 451; the new desk does not offer this feed.',
       'https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md','limited',
       steps=[('Check availability first','Use Binance only where the service is available to you. Binance and Binance.US are different services.'),('Check the installed tool’s help','The legacy alphad tool accepts --exchange binance with --market spot or --market perp. A parser existing in the software does not guarantee a reachable feed.'),('Respect connection errors','HTTP 451 is an access restriction, not a reason to change passwords or bypass the restriction. Choose a reachable supported source.')]),
crypto('kraken','Kraken','Public spot / separate futures API',
       'Kraken documents public and authenticated spot WebSocket endpoints. Its futures API is separate, so a spot connection must not be presented as futures coverage.',
       'https://docs.kraken.com/exchange/guides/websockets/introduction'),
crypto('bybit','Bybit','Product-specific public WebSockets',
       'Bybit documents separate public streams for spot, linear, inverse and options products, with distinct private streams. Alpharch has not implemented these routes.',
       'https://bybit-exchange.github.io/docs/v5/ws/connect'),
crypto('okx','OKX','Public / private WebSocket API',
       'OKX documents public and private WebSocket services. Endpoint selection and product availability must match the user’s regional account; Alpharch has no released OKX adapter.',
       'https://www.okx.com/docs-v5'),
crypto('bitget','Bitget','Public market WebSocket channels',
       'Bitget documents public ticker, candle, trade and depth channels without login. Account channels are separate; Alpharch has no Bitget adapter yet.',
       'https://www.bitget.com/api-doc/classic/quickStart/websocket-intro'),
crypto('gate','Gate','Public / private API v4',
       'Gate documents direct subscriptions to public channels and API-key authentication for private channels. Alpharch has not implemented a Gate connection.',
       'https://www.gate.com/docs/developers/apiv4/ws/en/'),
crypto('kucoin','KuCoin','Public market-data API',
       'KuCoin publishes several WebSocket interfaces and connection procedures. The chosen API family and account region must match; Alpharch does not yet implement a KuCoin adapter.',
       'https://www.kucoin.com/docs-new/websocket-api/base-info/introduction'),
crypto('crypto-com','Crypto.com Exchange','Exchange REST / WebSocket API',
       'Crypto.com Exchange documents separate user and market-data WebSocket services. Its Exchange API should not be confused with a login to another Crypto.com product.',
       'https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html'),
crypto('bitfinex','Bitfinex','Public market WebSocket channels',
       'Bitfinex documents public channel subscriptions separately from authenticated account operations. An Alpharch adapter has not been released.',
       'https://docs.bitfinex.com/docs/ws-public'),
crypto('bitmex','BitMEX','Public / authenticated WebSocket topics',
       'BitMEX publishes a WebSocket API with incremental table updates. Alpharch must implement its snapshots and updates before it can offer a reliable BitMEX feed.',
       'https://www.bitmex.com/app/wsAPI'),
]

PROVIDERS += [
entry('databento','Databento','Data & routing','Licensed live / historical data','Cross-platform client libraries','access',
      'Databento supplies live and historical market data through documented APIs. Alpharch’s development build has a CSV import path; that is not a live Databento connection.',
      ['Databento account access and the dataset/schema permissions needed for your market.','A released live adapter, or supported files for the development importer.'],
      [('Identify the dataset and schema','Confirm trades, depth or market-by-order coverage for the intended venue. These are distinct data products.'),('Separate import from live streaming','A downloaded CSV can be used only through a compatible importer. It does not establish a live feed.'),('Check Alpharch release support','The live adapter is not released. Development import support is documented with the application and should not be assumed present in the public installer.')],
      [('Historical data works but live data does not','Check live permissions and integration support independently.'),('A CSV does not contain individual orders','Inspect its schema. Aggregated depth or candle data cannot reconstruct missing MBO events.')],
      [('Databento data and API documentation','https://databento.com/docs'),('Live authentication','https://databento.com/docs/api-reference-live/gateway-control-messages/authentication-response?historical=python&live=raw')]),
entry('dxfeed','dxFeed','Data & routing','dxLink / contracted data service','Cross-platform WebSocket API','access',
      'dxFeed documents dxLink market-data connections with multiple authorization modes. A demo endpoint is not proof of live exchange entitlement or a working Alpharch adapter.',
      ['The contracted service endpoint and authentication supplied for your account.','The required exchange permissions and an implemented Alpharch adapter.'],
      [('Confirm the service','Ask which markets, depth and live or delayed permissions are included in the account.'),('Use the assigned access details','Endpoint and authorization must match the subscribed service. Credentials issued through another platform may not be portable.'),('Check Alpharch availability','No dxFeed adapter is released. Demo examples remain development references, not live production connections.')],
      [('Demo quotes appear but the contract is unavailable','Verify the service scope and entitlement before treating the feed as live.'),('Token rejected','Confirm the token’s intended endpoint, scope and expiry with the issuing provider.')],
      [('dxLink connection documentation','https://kb.dxfeed.com/en/market-data-api/dxlink.html'),('Token authorization','https://kb.dxfeed.com/en/data-services/real-time-and-delayed-services/token-based-authorization.html')]),
]

ALIASES = {'interactive-brokers':'ibkr ib gateway tws', 'ninjatrader':'ninja trader continuum',
           'amp-futures':'amp clearing', 'tastytrade':'tastyworks', 'crypto-com':'crypto.com',
           'gate':'gate.io', 'phillip-capital':'phillipcapital', 'schwab':'tos think or swim'}
for provider in PROVIDERS:
    provider['aliases'] = ALIASES.get(provider['slug'], '')
